### ISSUE TITLE
Hibernate Validator is not working

### ISSUE THREAD

**Issue by Niatomi** [Niatomi/spring-app#1]
Modules spring-forms-validator and spring-crud-app is basically the same module, except this fact in validator implemeted valid of java persistence. spring-crud-app works fine, but spring-forms-validator even with early Hibernate Validator Engine[6.0.0-6.1.6] give this
```java
SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/C:/Users/playe/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar!/] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:133)
	at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:60)
```
And because of this error Spring Config isn't working properly

**Comment by Niatomi** [comment]
Changed version of TomCat from 7.*.* to 9.0.6 
Now it works fine
